[build]
  publish = "."
  command = "echo 'No build process needed - static site'"

[build.environment]
  NODE_VERSION = "18"

# Redirects configuration
[[redirects]]
  from = "/"
  to = "/ru/"
  status = 301
  force = true

# Clean URLs для русской версии
[[redirects]]
  from = "/ru/"
  to = "/ru/index.html"
  status = 200

[[redirects]]
  from = "/ru/about"
  to = "/ru/about.html"
  status = 200

[[redirects]]
  from = "/ru/catalog"
  to = "/ru/catalog.html"
  status = 200

[[redirects]]
  from = "/ru/contact"
  to = "/ru/contact.html"
  status = 200

[[redirects]]
  from = "/ru/production"
  to = "/ru/production.html"
  status = 200

[[redirects]]
  from = "/ru/retail"
  to = "/ru/retail.html"
  status = 200

[[redirects]]
  from = "/ru/wholesale"
  to = "/ru/wholesale.html"
  status = 200

[[redirects]]
  from = "/ru/horeca"
  to = "/ru/horeca.html"
  status = 200

[[redirects]]
  from = "/ru/export"
  to = "/ru/export.html"
  status = 200

# Clean URLs для английской версии
[[redirects]]
  from = "/en/"
  to = "/en/index.html"
  status = 200

[[redirects]]
  from = "/en/about"
  to = "/en/about.html"
  status = 200

[[redirects]]
  from = "/en/catalog"
  to = "/en/catalog.html"
  status = 200

[[redirects]]
  from = "/en/contact"
  to = "/en/contact.html"
  status = 200

[[redirects]]
  from = "/en/production"
  to = "/en/production.html"
  status = 200

[[redirects]]
  from = "/en/retail"
  to = "/en/retail.html"
  status = 200

[[redirects]]
  from = "/en/wholesale"
  to = "/en/wholesale.html"
  status = 200

[[redirects]]
  from = "/en/horeca"
  to = "/en/horeca.html"
  status = 200

[[redirects]]
  from = "/en/export"
  to = "/en/export.html"
  status = 200

# Clean URLs для итальянской версии
[[redirects]]
  from = "/it/"
  to = "/it/index.html"
  status = 200

[[redirects]]
  from = "/it/about"
  to = "/it/about.html"
  status = 200

[[redirects]]
  from = "/it/catalog"
  to = "/it/catalog.html"
  status = 200

[[redirects]]
  from = "/it/contact"
  to = "/it/contact.html"
  status = 200

[[redirects]]
  from = "/it/production"
  to = "/it/production.html"
  status = 200

[[redirects]]
  from = "/it/retail"
  to = "/it/retail.html"
  status = 200

[[redirects]]
  from = "/it/wholesale"
  to = "/it/wholesale.html"
  status = 200

[[redirects]]
  from = "/it/horeca"
  to = "/it/horeca.html"
  status = 200

[[redirects]]
  from = "/it/export"
  to = "/it/export.html"
  status = 200

# Clean URLs для польской версии
[[redirects]]
  from = "/pl/"
  to = "/pl/index.html"
  status = 200

[[redirects]]
  from = "/pl/about"
  to = "/pl/about.html"
  status = 200

[[redirects]]
  from = "/pl/catalog"
  to = "/pl/catalog.html"
  status = 200

[[redirects]]
  from = "/pl/contact"
  to = "/pl/contact.html"
  status = 200

[[redirects]]
  from = "/pl/production"
  to = "/pl/production.html"
  status = 200

[[redirects]]
  from = "/pl/retail"
  to = "/pl/retail.html"
  status = 200

[[redirects]]
  from = "/pl/wholesale"
  to = "/pl/wholesale.html"
  status = 200

[[redirects]]
  from = "/pl/horeca"
  to = "/pl/horeca.html"
  status = 200

[[redirects]]
  from = "/pl/export"
  to = "/pl/export.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
